name: Laravel

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  upload-hosting:
    
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.1.0
        with:
          fetch-depth: 2

      - name: Create env file
        run: |
                touch .env
                echo APP_NAME=MyAppName >> .env
                echo APP_ENV=production >> .env
                echo APP_DEBUG=false >> .env
                echo LOG_CHANNEL=daily >> .env
                echo DB_DATABASE=${{ secrets.DEV_DB_DATABASE }} >> .env
                echo DB_USERNAME=${{ secrets.DEV_DB_USERNAME }} >> .env
                echo DB_PASSWORD=${{ secrets.DEV_DB_PASSWORD }} >> .env
                echo "!.env" > .git-ftp-include

      - name: Cache dependencies
        uses: actions/cache@v1
        with:
              path: ~/.composer/cache/files
              key: dependencies-composer-${{ hashFiles('composer.json') }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
              php-version: 7.3
              extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite
              coverage: none

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-interaction --no-suggest

      - name: Adding Vendor
        run: echo "!vendor/" > .git-ftp-include

      - name: FTP Deploy Action
        uses: SamKirkland/FTP-Deploy-Action@3.1.1
        with:
          ftp-server: ftp://${{ secrets.DEV_FTP_SERVER }}
          ftp-username: ${{ secrets.DEV_FTP_USERNAME }}
          ftp-password: ${{ secrets.DEV_FTP_PASSWORD }}
